import type { Metadata } from "next";
import "./globals.css";
import { Inter as GeistSans } from 'next/font/google';
import { Roboto_Mono as GeistMono } from 'next/font/google';

const sans = GeistSans({
  subsets: ['latin'],
  variable: '--font-geist-sans',
});

const mono = GeistMono({
  subsets: ['latin'],
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${sans.variable} ${mono.variable}`}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}